//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Professional_IIS_7.asp_net_mvc_5_samples.Chapter_14.S1402.VM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderLines = new HashSet<OrderLine>();
        }
    
        public string OrderId { get; set; }
        public string UserName { get; set; }
        public System.DateTime OrderTime { get; set; }
    
        public virtual ICollection<OrderLine> OrderLines { get; set; }
    }
}
